### ISSUE TITLE
Temporizadores

### ISSUE THREAD

**Issue by amujika** [Sulley38/gravity-ds#1]
Hace falta un segundo temporizador para la animación de correr, que cambie la imagen del tío cada poco para crear la animación.

**Comment by Sulley38** [comment]
Entiendo. Me pondré a ello el fin de semana.

**Comment by Sulley38** [comment]
Pensándolo mejor, no estoy seguro de que esto sea necesario. El framerate se calcula por interrupción; cada vez que hay un nuevo vblank se suma un frame. Así limitamos los fps a lo que nos convenga. La animación, si he entendido bien, habría que hacerla contando los frames, no segundos. Es correcto?

**Comment by Sulley38** [comment]
A ver si te sirve lo que hay. La consola va a 60fps por defecto. Podríamos bajarlo a 30fps sin mayor problema si hiciera falta.
Puedes hacer que al llegar al frame 30 (medio segundo) cambie la imagen del monigote para crear la animación. O algo así. Yo que sé xD
Si te paras a pensar, no haría falta ni el temporizador. Cuentas hasta 60 frames, y eso es un segundo.
En principio cierro el ticket, si lo crees conveniente reabre.
